// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	about "frontend/biz/router/about"
	auth "frontend/biz/router/auth"
	cart "frontend/biz/router/cart"
	category "frontend/biz/router/category"
	checkout "frontend/biz/router/checkout"
	eino "frontend/biz/router/eino"
	home "frontend/biz/router/home"
	order "frontend/biz/router/order"
	product "frontend/biz/router/product"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	eino.Register(r)

	about.Register(r)

	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	category.Register(r)

	product.Register(r)

	auth.Register(r)

	home.Register(r)
}
