// Code generated by hertz generator.

package eino

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _einoMw() []app.HandlerFunc {
	// your code...
	return nil
}
